config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :words

  get 'today_words', to: 'words#today_words'
  get '/words/:id/flash_card', to: 'words#flash_card', as: 'flash_card'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "words#today_words"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/word_concern.rb
module WordConcern
  module Constants
    LEVEL_OF_DIFFICULTIES = [
      [I18n.t('word.level_of_difficulties.easy'), 0],
      [I18n.t('word.level_of_difficulties.medium'), 1],
      [I18n.t('word.level_of_difficulties.hard'), 2]
    ]
  end
end

app/models/learning_attempt.rb
class LearningAttempt < ApplicationRecord
  belongs_to :word
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :words
  has_many :learning_attempts

  # Other filters
  # has_many :proficient_words, -> { where(learning_attempts: {proficient: true}) }, through: :learning_attempts, source: :word
  # ...
  # has_many :learning_attempts_today, -> { where(learning_attempts: {created_at: Time.zone.now.all_day}) }, through: :learning_attempts, source: :word
  # ...
end

app/models/word.rb
class Word < ApplicationRecord

  include WordConcern::Constants

  after_create :set_upcoming_learn_at

  belongs_to :user

  has_rich_text :meaning

  has_many :learning_attempts


  validates :word, presence: true
  validates :meaning, presence: true

  # Other filters (to be defined in the future)
  # has_many :learning_attemps_true, -> { where(learning_attempts: {proficient: true}) }, through: :learning_attempts, source: :word
  # ...

  def self.today_words
    # Get list of words should be learned today
    Word.where(upcoming_learn_at: Time.zone.now.all_day)
  end

  def pronucation_link
    ''
  end

  def sample_sentence
    ''
  end

  def self.random_words(word)
    # Get 3 random words
    random_words = self.where.not(id: word.id).sample(3)
    random_words << word
    random_words.shuffle
  end

  # Get list of level of difficulties
  def self.list_level_of_difficulties
    LEVEL_OF_DIFFICULTIES
  end


  private

  def set_upcoming_learn_at
    # Set upcoming_learn_at based on the last learning attempt
    # TODO
    CalculateNextTimeToLearnTheWordJob.set(wait: 1.minute).perform_later(self)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/learning_attempt_controller.rb
class LearningAttemptController < ApplicationController

  before_action :set_attempt, only: [:show, :create]

  def show

  end

  def new
    @learning_attempt = LearningAttempt.new
  end

  def index
    @learning_attempts = LearningAttempt.all
  end

  def create
    @learning_attempt = LearningAttempt.new(learning_attempt_params)
    if @learning_attempt.save
      redirect_to learning_attempt_path(@learning_attempt)
    else
      render :new
    end
  end

  private

  def set_attempt
    @learning_attempt = LearningAttempt.find(params[:id])
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController

  # Include Pagy for pagination
  include Pagy::Backend

  # Include FlashCardBuilder
  # include Builders::FlashCardBuilder

  before_action :set_word, only: %i[ show edit update destroy flash_card ]

  # Get /today or /today.json
  # Get today's words to learn
  def today_words
    @words = Word.today_words
  end

  def flash_card
    @word, @random_words = FlashCardBuilder.build(@word)
  end

  # GET /words or /words.json
  def index
    @pagy, @words = pagy(Word.where(:user => current_user).order(:created_at => :desc))
  end

  # GET /words/1 or /words/1.json
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words or /words.json
  def create
    @word = Word.new(word_params)
    @word.user = current_user

    respond_to do |format|
      if @word.save
        format.html { redirect_to word_url(@word), notice: "Word was successfully created." }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1 or /words/1.json
  def update
    @word.user = current_user
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to word_url(@word), notice: "Word was successfully updated." }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1 or /words/1.json
  def destroy
    @word.destroy

    respond_to do |format|
      format.html { redirect_to words_url, notice: "Word was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def word_params
      params.require(:word).permit(:word, :pronunciation, :meaning, :level_of_difficult)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/learning_attempt_helper.rb
module LearningAttemptHelper
end

app/helpers/words_helper.rb
module WordsHelper
  include Pagy::Frontend
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t :application_name %></title>
    <%= favicon_link_tag image_path('favicon.png') %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>

    <%= yield :custom_stylesheet %>
    <%= hotwire_livereload_tags if Rails.env.development? %>
  </head>

  <body>

    <div class="container">
      <!-- Navigation bar -->
      <% if current_user %>
        <nav class="navbar bg-body-tertiary">
          <div class="container-fluid">
            <a class="navbar-brand" href="<%= root_path %>"><%= t :applicattion_short_name %></a>
            <div class="float-end">
              <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-outline-danger" %>
            </div>
          </div>
        </nav>

      <% end %>
      <!-- End of Navigation bar -->
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t :application_name %></title>
    <%= favicon_link_tag image_path('favicon.png') %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= yield :custom_stylesheet %>
    <%= hotwire_livereload_tags if Rails.env.development? %>
  </head>

  <body>

    <div class="container">
      <!-- Navigation bar -->
      <% if current_user %>
        <nav class="navbar bg-body-tertiary">
          <div class="container-fluid">
            <a class="navbar-brand" href="<%= root_path %>"><%= t :applicattion_short_name %></a>
            <div class="float-end">
              <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-outline-danger" %>
            </div>
          </div>
        </nav>

      <% end %>
      <!-- End of Navigation bar -->
      <div class="card mt-3">
        <div class="card-body">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/words/_form.html.erb
<%= form_with(model: word) do |form| %>
  <% if word.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
        <% word.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-6">
      <div class="mb-3">
        <%= form.label :word, style: "display: block" %>
        <%= form.text_field :word, :class => "form-control" %>
      </div>
    </div>
    <div class="col-6">
      <div class="mb-3">
        <%= form.label :pronunciation, style: "display: block" %>
        <%= form.text_field :pronunciation, :class => "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="mb-3">
      <%= form.label :meaning %>
      <%= form.rich_text_area :meaning %>
    </div>
  </div>

  <div class="row">
    <div class="mb-3">
      <%= form.label :level_of_difficult, style: "display: block" %>
      <%= form.select(:level_of_difficult, Word.list_level_of_difficulties, { :class => "form-group" }) %>
    </div>
  </div>

  <div class="d-grid">
    <%= form.submit "Add", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/words/_list.html.erb
<div class="row">
  <div class="col-2">
    <h3>Word</h3>
  </div>
  <div class="col-2">
    <h3>Pronunciation</h3>
  </div>
  <div class="col-4">
    <h3>Meaning</h3>
  </div>
  <div class="col-2">
    <h3>Level of Difficult</h3>
  </div>
  <div class="col-2">
    <h3>Actions</h3>
  </div>
</div>
<div id="words">
  <% @words.each do |word| %>
    <%= render partial: "word_list_item", locals: {word: word} %>
  <% end %>
</div>

app/views/words/_word.html.erb
<div id="<%= dom_id word %>">
  <h1><%= word.word %></h1>

  <p>
    <strong>Pronunciation:</strong>
    <%= word.pronunciation %>
  </p>

  <p>
    <strong>Meaning:</strong>
    <%= word.meaning %>
  </p>

  <p>
    <strong>Level of difficult:</strong>
    <%= word.level_of_difficult %>
  </p>
</div>

app/views/words/_word_list_item.html.erb
<% content_for :custom_stylesheet do %>
  <%= stylesheet_link_tag 'words' %>
<% end %>

<div id="<%= dom_id word %>" class="row rounded mt-2 word-list-item">

  <div class="col-2">
    <%= link_to word.word, word %>
  </div>

  <div class="col-2">
    <%= word.pronunciation %>
  </div>

  <div class="col-4">
    <%= word.meaning %>
  </div>

  <div class="col-2">
    <%= word.level_of_difficult %>
  </div>

  <div class="col-2">
    <%= link_to 'Pronounce' %>
    |
    <%= link_to 'Example with chatGPT' %>
    |
    <%= link_to 'Flashcard', flash_card_path(word) %>
  </div>
</div>

app/views/words/edit.html.erb
<div class="row mt-3">
  <div class="card">
    <div class="card-body">
      <h1>Editing word</h1>

      <%= render "form", word: @word %>

      <div>
        <%= link_to "Show this word", @word %> |
        <%= link_to "Back to words", words_path %>
      </div>
    </div>
  </div>
</div>

app/views/words/flash_card.html.erb
<%= link_to t(:back), root_path %>

<div>
  <div class="row">
    <h1> Which word is this? </h1>
    <p>
    <%= @word.meaning %>
    </p>
  </div>

  <div class="row">
    <% @random_words.each do |word| %>
      <div class="card text-bg-light ms-3" style="max-width: 18rem;">
        <div class="card-body">
          <h3 class="card-title"><%= word.word %></h5>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/words/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>All words</h1>

<div class="row">
  <%= link_to "Today words", today_words_path %>
</div>

<%= link_to "Add new word", new_word_path, :class => "btn btn-primary" %>

<div class="mt-3">
  <%= render "words/list" %>
</div>

<div class="justify-content-center">
  <%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/words/new.html.erb
<h1>New word</h1>

<%= render "form", word: @word %>

<br>

<div>
  <%= link_to "Back to words", words_path %>
</div>

app/views/words/show.html.erb
<div class="row mt-3 justify-content-md-center">
  <p style="color: green"><%= notice %></p>
  <div class="card">
    <div class="card-body">

      <%= render @word %>

      <div>
        <div class="row">
          <%= link_to "Edit this word", edit_word_path(@word) %>
          <%= link_to "Back to words", words_path %>
        </div>

        <div class="row">
          <%= button_to "Destroy this word", @word, class: "btn btn-danger", method: :delete %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/words/today_words.html.erb
<h1>Words to learn today</h1>

<%= link_to "Add new word", new_word_path, :class => "btn btn-primary" %>

<%= render 'words/list' %>

<%= link_to "All words", words_path %>